 document      =  { SOI ~ source_file ~ EOI }
source_file   =  _{ forest | block }
block         =  { statement* }
global_block  =  { "global" ~ "{" ~ strong_init* ~"}" }
strong_init   =  { (sized_declaration | type_name ~ initialization) ~ ";"}

forest 		  = { (function | global_block)+ }
bracket_block =  { "{" ~ block ~ "}" }
newline       = _{ "\n" | "\r" }
WHITESPACE    = _{ " " | "\t" | "\n" | "\r" }

fn_arg  = {type_name ~ ident ~ array_dimension*}
fn_arg_list = {(fn_arg ~ ("," ~ fn_arg)*)?}
fn_header = { "func" ~ ident ~ "(" ~ fn_arg_list ~ ")" ~ ("->" ~ type_name)? }
function      =  { fn_header ~ "{" ~ block ~ "}" }

statement      =  { (command | init_statement | if_statement | for_statement | while_statement | return_statement | break_statement | continue_statement) }
command        =  { function_call ~ ";" }
function_call  =  { ident ~ "(" ~ params? ~ ")" }
params         = _{ argument ~ ("," ~ argument)* }
argument       = _{ named_argument | expression }
named_argument = { ident ~ ":" ~ expression }
init_statement =  { (sized_declaration | type_name? ~ initialization) ~ ";" }
sized_declaration = { type_name ~ ident ~ array_dimension+ ~ ("=" ~ expression)? }
array_dimension = { "[" ~ integer ~ "]" }
initialization =  { noun ~ "=" ~ expression }
const_key      =  {"const"}

if_statement    =  { "if" ~ "(" ~ expression ~ ")" ~ bracket_block ~ else_block?}
else_block      = _{ "else" ~ (if_statement | bracket_block) }
for_statement   =  { "for" ~ ident ~ "in" ~ (range | expression) ~ bracket_block }
range           =  { "(" ~ expression ~ ".." ~ expression ~ ")" }
numVar          = _{ integer | noun }
while_statement =  { "while" ~ "(" ~ expression ~ ")" ~ bracket_block }
return_statement = { "return" ~ expression ~ ";" }
break_statement = { "break" ~ ";" }
continue_statement = { "continue" ~ ";" }

type_name      =  { const_key? ~ (array_type | primitive_type) }
primitive_type = { "bool" | "int" | "color" | "float" | "string" }
array_type   = { "array<" ~ type_name ~ "," ~ integer ~ ">" }

number     = { decimal | integer }
expression = {
	dyadicExpr
  | monadicExpr
  | term
}

monadicExpr  = { operator ~ term }
dyadicExpr   = { (monadicExpr | term) ~ operator ~ expression }
parenth_expr = { "(" ~ expression ~ ")" }

box = {"[" ~ expression ~ "]" }
noun = {ident ~ box* }
term = _{ decimal | integer | string_literal | color | boolean | key | function_call | noun | array_literal | expanded_array_literal | parenth_expr }

operator = {
  | "+"
  | "*"
  | "-"
  | "/"
  | "%"
  | ">="
  | "<="
  | "!="
  | "<"
  | ">"
  | "=="
  | "&&"
  | "||"
  | "!"
}
string_literal = @{ "\"" ~ ("\\" ~ ANY | !("\"" | "\\") ~ ANY)* ~ "\"" }
array_literal = { "{" ~ (term ~ ("," ~ term)*)?  ~ "}" }
expanded_array_literal = { "{" ~ term ~ "..." ~ "}" }
boolean = { "true" | "false" }
color = @{"Color::" ~ ident}
key   = @{"Key::" ~ ident}
integer = @{ "-"? ~ ASCII_DIGIT+ }
decimal = @{ "-"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }
ident   = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }
